spring:
  application:
    name: manage-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  boot:
#    admin:
#      client:
#        service-base-url: http://192.168.3.100:9002
#      url:  http://192.168.3.100:9002
  zipkin:
    base-url: http://192.168.3.100:9001
  output.ansi.enabled: always
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 50Mb
  rabbitmq:
      host: 192.168.3.132
      port: 5672
      username: guest
      password: guest
      publisher-confirms: false
      publisher-returns: true
      virtual-host: /

eureka:
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
    client:
      registry-fetch-interval-seconds: 15
      service-url:
        defaultZone:  http://192.168.3.100:38130/eureka/,http://192.168.3.132:38130/eureka/

management:
  security:
    enabled:  false


#请求处理的超时时间
ribbon:
  ReadTimeout: 120000
#请求连接的超时时间
  ConnectTimeout: 30000

feign.hystrix.enabled: true

#hystrix 熔断机制
hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

logging:
  level:
    com.zhou.medical: debug