server.port: 38120
spring:
  application:
    name: config-server
  cloud.config:
      server:
        git:
          uri: https://github.com/zhouzhouluo/microservicecloud-config.git
        searchPaths: repo
      label:  master

eureka:
    instance:
      lease-renewal-interval-in-seconds: 30
    client:
      registry-fetch-interval-seconds: 15
      service-url:
        defaultZone:  http://127.0.0.1:38130/eureka/

management:
  security:
    enabled: false

#enforce config-service security
#security:
#  user:
#    name: zhouzhouluo
#    password: zhouzhouluo

