server.port: 9004
spring:
  application:
    name: config-server
  boot:
    admin:
      url:  http://localhost:9002
  cloud.config:
      server:
        git:
          uri: https://github.com/backkoms/spring-cloud-repo
        searchPaths: repo
      label:  master

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
    instance:
      lease-renewal-interval-in-seconds: 30
    client:
      registry-fetch-interval-seconds: 15
      service-url:
        defaultZone:  http://localhost:9003/eureka/

management:
  security:
    enabled:  false

#enforce config-service security
security:
  user:
    name: user
    password: yourPW

logging:
  level:
    tk:
      mybatis:  TRACE
