server:
  port: 9004
logging:
  level:
    tk:
      mybatis:  TRACE

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/backkoms/spring-cloud-repo
        searchPaths: repo
      label:  master
  boot:
    admin:
      url:  http://localhost:9002

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:9003/eureka/
management:
  security:
    enabled:  false

#enforce config-service security
security:
  user:
    name: user
    password: yourPW
