server:
  port: 38110
logging:
  level:
    tk:
      mybatis: TRACE

spring:
  application:
    name: admin-server
  output:
      ansi:
        enabled:  ALWAYS
  boot:
    admin:
      turbine:
        clusters: default
        url:  http://192.168.3.100:8031/turbine.stream
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti
eureka:
  instance:
    lease-renewal-interval-in-seconds:  30
  client:
    registry-fetch-interval-seconds:  15
    service-url:
      defaultZone:  http://192.168.3.100:9003/eureka/,http://192.168.3.132:38130/eureka/