server:
  #端口号
  port: 9001
#项目名，如果不设定，默认是 /
#  context-path: /log-service

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
      name: master
      url: jdbc:mysql://192.168.214.111:3306/hsp?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: gmcc
      password: hsp10086
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true
      name: slave
      url: jdbc:mysql://192.168.214.111:3306/hsp?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: gmcc
      password: hsp10086


logging:
  level:
    com.cmcc.hsp: debug