spring:
  application:
    name: operation-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
      name: master
      url: jdbc:mysql://127.0.0.1:3306/medicalcare?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      initialSize: 5
      minIdle: 5
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery: SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true
      name: slave
      url: jdbc:mysql://127.0.0.1:3306/medicalcare?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery: SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

#  boot:
#      admin:
#        client:
#          service-base-url: http://192.168.3.100:9002
#        url:  http://192.168.3.100:9002
  zipkin:
    base-url: http://192.168.3.132:9001
  rabbitmq:
        host: 192.168.3.132
        port: 5672
        username: guest
        password: guest
        publisher-confirms: false
        publisher-returns: false
        virtual-host: /

eureka:
    instance:
      preferIpAddress: true
      lease-renewal-interval-in-seconds: 30
    client:
      registry-fetch-interval-seconds: 15
      service-url:
        defaultZone:  http://192.168.3.100:38130/eureka/,http://192.168.3.132:38130/eureka/

management:
  security:
    enabled:  false

logging:
  level:
    com.zhou.medical: debug