server.port: 9001
spring:
  application:
    name: zipkin-server
  boot:
    admin:
      url: http://192.168.3.100:9002

eureka:
  instance:
    lease-renewal-interval-in-seconds:  30
  client:
    registry-fetch-interval-seconds:  15
    service-url:
      defaultZone: http://192.168.3.100:9003/eureka/

management:
  security:
    enabled:  false