server:
  port: 38130

spring:
  application:
    name: eureka-server
  boot:
    admin:
      url: http://192.168.3.132:38110

eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone:  192.168.3.132:${server.port}/eureka/
  server:
    enable-self-preservation: false

management:
  security:
    enabled: false