server:
  #端口号
  port: 38240
  #项目名，如果不设定，默认是 /
#  context-path: /log-service

spring:
  application:
    name: log-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
  boot:
      admin:
        client:
          service-base-url: http://192.168.3.132:38110
        url:  http://192.168.3.132:38110


  zipkin:
    base-url: http://192.168.3.132:38170
  data:
    mongodb:
      uri: mongodb://root:root@192.168.3.132:27017/test
  rabbitmq:
    host: 192.168.3.132
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /

eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone:  http://192.168.3.100:38130/eureka/,http://192.168.3.132:38130/eureka/

management:
  security:
    enabled:  false

logging:
  level:
    com.zhou.medical: debug