package com.zhou.medical.common.entity.log;

import java.util.Date;

public class JiuzhoutongLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhoutong_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhoutong_log.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhoutong_log.param
     *
     * @mbggenerated
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhoutong_log.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhoutong_log.exception
     *
     * @mbggenerated
     */
    private String exception;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhoutong_log.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiuzhoutong_log.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhoutong_log.id
     *
     * @return the value of jiuzhoutong_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhoutong_log.id
     *
     * @param id the value for jiuzhoutong_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhoutong_log.url
     *
     * @return the value of jiuzhoutong_log.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhoutong_log.url
     *
     * @param url the value for jiuzhoutong_log.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhoutong_log.param
     *
     * @return the value of jiuzhoutong_log.param
     *
     * @mbggenerated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhoutong_log.param
     *
     * @param param the value for jiuzhoutong_log.param
     *
     * @mbggenerated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhoutong_log.result
     *
     * @return the value of jiuzhoutong_log.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhoutong_log.result
     *
     * @param result the value for jiuzhoutong_log.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhoutong_log.exception
     *
     * @return the value of jiuzhoutong_log.exception
     *
     * @mbggenerated
     */
    public String getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhoutong_log.exception
     *
     * @param exception the value for jiuzhoutong_log.exception
     *
     * @mbggenerated
     */
    public void setException(String exception) {
        this.exception = exception == null ? null : exception.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhoutong_log.createtime
     *
     * @return the value of jiuzhoutong_log.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhoutong_log.createtime
     *
     * @param createtime the value for jiuzhoutong_log.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiuzhoutong_log.updatetime
     *
     * @return the value of jiuzhoutong_log.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiuzhoutong_log.updatetime
     *
     * @param updatetime the value for jiuzhoutong_log.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}